-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 22, 2024 at 06:02 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_admission`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int(100) NOT NULL,
  `username` varchar(200) NOT NULL,
  `password` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `username`, `password`) VALUES
(15, 'Admin', '12345678');

-- --------------------------------------------------------

--
-- Table structure for table `student`
--

CREATE TABLE `student` (
  `id` int(100) NOT NULL,
  `regno` varchar(100) NOT NULL,
  `tcno` int(200) NOT NULL,
  `sname` varchar(200) NOT NULL,
  `gname` varchar(200) NOT NULL,
  `contact` varchar(50) NOT NULL,
  `address` varchar(2000) NOT NULL,
  `community` varchar(500) NOT NULL DEFAULT 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES',
  `cast` varchar(100) NOT NULL,
  `dob` date NOT NULL,
  `class` varchar(10) NOT NULL,
  `shift` varchar(100) NOT NULL,
  `grad` varchar(200) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `blgroup` varchar(5) NOT NULL,
  `division` varchar(50) NOT NULL,
  `religion` varchar(50) NOT NULL,
  `doa` date NOT NULL,
  `college` varchar(200) NOT NULL DEFAULT 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI',
  `nation` varchar(50) NOT NULL DEFAULT 'INDIAN',
  `lastyear` varchar(100) NOT NULL,
  `highclass` varchar(500) NOT NULL DEFAULT 'Refer Mark Sheets',
  `fees` varchar(50) NOT NULL,
  `scholarship` varchar(50) NOT NULL,
  `medical` varchar(50) NOT NULL,
  `medium` varchar(50) NOT NULL DEFAULT 'English',
  `lid` date DEFAULT NULL,
  `tcapply` date DEFAULT NULL,
  `tcd` date DEFAULT NULL,
  `conduct` varchar(100) NOT NULL,
  `acdyear` varchar(200) NOT NULL,
  `tc_generated` tinyint(1) DEFAULT 0,
  `admno` varchar(200) NOT NULL,
  `addept` varchar(200) NOT NULL,
  `adyear` varchar(200) NOT NULL,
  `tcyear` varchar(200) NOT NULL,
  `status` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `student`
--

INSERT INTO `student` (`id`, `regno`, `tcno`, `sname`, `gname`, `contact`, `address`, `community`, `cast`, `dob`, `class`, `shift`, `grad`, `gender`, `blgroup`, `division`, `religion`, `doa`, `college`, `nation`, `lastyear`, `highclass`, `fees`, `scholarship`, `medical`, `medium`, `lid`, `tcapply`, `tcd`, `conduct`, `acdyear`, `tc_generated`, `admno`, `addept`, `adyear`, `tcyear`, `status`) VALUES
(1, '61072211901', 1, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-11-26', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', ' ', 'Refer Mark Sheets', 'Yes', 'Yes', 'Yes', 'English', '0000-00-00', '0000-00-00', '0000-00-00', '', '', 0, '2021cse001', '', '', '', 'Discontinue'),
(2, '61072211902', 2, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-11-27', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse002', '', '', '', ''),
(3, '61072211903', 3, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-11-28', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse003', '', '', '', ''),
(4, '61072211904', 4, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-11-29', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse004', '', '', '', ''),
(5, '61072211905', 5, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-11-30', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse005', '', '', '', ''),
(6, '61072211906', 6, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-01', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse006', '', '', '', ''),
(7, '61072211907', 7, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-02', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse007', '', '', '', ''),
(8, '61072211908', 8, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-03', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse008', '', '', '', ''),
(9, '61072211909', 9, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-04', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse009', '', '', '', ''),
(10, '61072211910', 10, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-05', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse010', '', '', '', ''),
(11, '61072211911', 11, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-06', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse011', '', '', '', ''),
(12, '61072211912', 12, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-07', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse012', '', '', '', ''),
(13, '61072211913', 13, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-08', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse013', '', '', '', ''),
(14, '61072211914', 14, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-09', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse014', '', '', '', ''),
(15, '61072211915', 15, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-10', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse015', '', '', '', ''),
(16, '61072211916', 16, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-11', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse016', '', '', '', ''),
(17, '61072211917', 17, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-12', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse017', '', '', '', ''),
(18, '61072211918', 18, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2001-12-13', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse018', '', '', '', ''),
(19, '61072211919', 19, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-14', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse019', '', '', '', ''),
(20, '61072211920', 20, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-15', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse020', '', '', '', ''),
(21, '61072211921', 21, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-16', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse021', '', '', '', ''),
(22, '61072211922', 22, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-17', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse022', '', '', '', ''),
(23, '61072211923', 23, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-18', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse023', '', '', '', ''),
(24, '61072211924', 24, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-19', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse024', '', '', '', ''),
(25, '61072211925', 25, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-20', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse025', '', '', '', ''),
(26, '61072211926', 26, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-21', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse026', '', '', '', ''),
(27, '61072211927', 27, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-22', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse027', '', '', '', ''),
(28, '61072211928', 28, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-23', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse028', '', '', '', ''),
(29, '61072211929', 29, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-24', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse029', '', '', '', ''),
(30, '61072211930', 30, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-25', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse030', '', '', '', ''),
(31, '61072211931', 31, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-26', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse031', '', '', '', ''),
(32, '61072211932', 32, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-27', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse032', '', '', '', ''),
(33, '61072211933', 33, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-28', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse033', '', '', '', ''),
(34, '61072211934', 34, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-29', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse034', '', '', '', ''),
(35, '61072211935', 35, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-30', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse035', '', '', '', ''),
(36, '61072211936', 36, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2001-12-31', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse036', '', '', '', ''),
(37, '61072211937', 37, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-01', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse037', '', '', '', ''),
(38, '61072211938', 38, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-02', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse038', '', '', '', ''),
(39, '61072211939', 39, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-03', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse039', '', '', '', ''),
(40, '61072211940', 40, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-04', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse040', '', '', '', ''),
(41, '61072211941', 41, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-05', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse041', '', '', '', ''),
(42, '61072211942', 42, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-06', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse042', '', '', '', ''),
(43, '61072211943', 43, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-07', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse043', '', '', '', ''),
(44, '61072211944', 44, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-08', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse044', '', '', '', ''),
(45, '61072211945', 45, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-09', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse045', '', '', '', ''),
(46, '61072211946', 46, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-10', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse046', '', '', '', ''),
(47, '61072211947', 47, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-01-11', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse047', '', '', '', ''),
(48, '61072211948', 48, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-12', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse048', '', '', '', ''),
(49, '61072211949', 49, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-13', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse049', '', '', '', ''),
(50, '61072211950', 50, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-14', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse050', '', '', '', ''),
(51, '61072211951', 51, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-15', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse051', '', '', '', ''),
(52, '61072211952', 52, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-16', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse052', '', '', '', ''),
(53, '61072211953', 53, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-17', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse053', '', '', '', ''),
(54, '61072211954', 54, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-18', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse054', '', '', '', ''),
(55, '61072211955', 55, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-19', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse055', '', '', '', ''),
(56, '61072211956', 56, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-20', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse056', '', '', '', ''),
(57, '61072211957', 57, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-21', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse057', '', '', '', ''),
(58, '61072211958', 58, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-22', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse058', '', '', '', ''),
(59, '61072211959', 59, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-23', '', '', 'B.E', 'Female', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse059', '', '', '', ''),
(60, '61072211960', 60, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-24', '', '', 'B.E', 'Male', '', 'ComputerScienceEngneering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021cse060', '', '', '', ''),
(61, '61072211961', 61, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-25', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee001', '', '', '', ''),
(62, '61072211962', 62, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-26', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee002', '', '', '', ''),
(63, '61072211963', 63, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-27', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee003', '', '', '', ''),
(64, '61072211964', 64, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-28', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee004', '', '', '', ''),
(65, '61072211965', 65, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-29', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee005', '', '', '', ''),
(66, '61072211966', 66, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-01-30', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee006', '', '', '', ''),
(67, '61072211967', 67, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-01-31', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee007', '', '', '', ''),
(68, '61072211968', 68, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-01', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee008', '', '', '', ''),
(69, '61072211969', 69, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-02', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee009', '', '', '', ''),
(70, '61072211970', 70, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-03', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee010', '', '', '', ''),
(71, '61072211971', 71, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-04', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee011', '', '', '', ''),
(72, '61072211972', 72, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-05', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee012', '', '', '', ''),
(73, '61072211973', 73, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-06', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee013', '', '', '', ''),
(74, '61072211974', 74, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-07', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee014', '', '', '', ''),
(75, '61072211975', 75, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-08', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee015', '', '', '', ''),
(76, '61072211976', 76, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-09', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee016', '', '', '', ''),
(77, '61072211977', 77, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-10', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee017', '', '', '', ''),
(78, '61072211978', 78, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-11', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee018', '', '', '', ''),
(79, '61072211979', 79, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-12', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee019', '', '', '', ''),
(80, '61072211980', 80, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-13', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee020', '', '', '', ''),
(81, '61072211981', 81, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-14', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee021', '', '', '', ''),
(82, '61072211982', 82, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-15', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee022', '', '', '', ''),
(83, '61072211983', 83, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-16', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee023', '', '', '', ''),
(84, '61072211984', 84, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-17', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee024', '', '', '', ''),
(85, '61072211985', 85, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-18', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee025', '', '', '', ''),
(86, '61072211986', 86, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-19', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee026', '', '', '', ''),
(87, '61072211987', 87, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-20', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee027', '', '', '', ''),
(88, '61072211988', 88, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-21', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee028', '', '', '', ''),
(89, '61072211989', 89, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-22', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee029', '', '', '', ''),
(90, '61072211990', 90, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-23', '', '', 'B.E', 'Male', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee030', '', '', '', ''),
(91, '61072211991', 91, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-24', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee031', '', '', '', ''),
(92, '61072211992', 92, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-25', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee032', '', '', '', ''),
(93, '61072211993', 93, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-26', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee033', '', '', '', ''),
(94, '61072211994', 94, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-27', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee034', '', '', '', ''),
(95, '61072211995', 95, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-02-28', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee035', '', '', '', ''),
(96, '61072211996', 96, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-01', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee036', '', '', '', ''),
(97, '61072211997', 97, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-02', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee037', '', '', '', ''),
(98, '61072211998', 98, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-03', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee038', '', '', '', ''),
(99, '61072211999', 99, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-04', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee039', '', '', '', ''),
(100, '61072212000', 100, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-05', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee040', '', '', '', ''),
(101, '61072212001', 101, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-06', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee041', '', '', '', ''),
(102, '61072212002', 102, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-07', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee042', '', '', '', ''),
(103, '61072212003', 103, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-08', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee043', '', '', '', ''),
(104, '61072212004', 104, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-09', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee044', '', '', '', ''),
(105, '61072212005', 105, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-10', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee045', '', '', '', ''),
(106, '61072212006', 106, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-11', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee046', '', '', '', ''),
(107, '61072212007', 107, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-12', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee047', '', '', '', ''),
(108, '61072212008', 108, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-13', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee048', '', '', '', ''),
(109, '61072212009', 109, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-14', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee049', '', '', '', ''),
(110, '61072212010', 110, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-15', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee050', '', '', '', ''),
(111, '61072212011', 111, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-03-16', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee051', '', '', '', ''),
(112, '61072212012', 112, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-17', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee052', '', '', '', ''),
(113, '61072212013', 113, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-18', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee053', '', '', '', ''),
(114, '61072212014', 114, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-19', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee054', '', '', '', ''),
(115, '61072212015', 115, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-20', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee055', '', '', '', ''),
(116, '61072212016', 116, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-21', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee056', '', '', '', ''),
(117, '61072212017', 117, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-22', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee057', '', '', '', ''),
(118, '61072212018', 118, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-23', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee058', '', '', '', ''),
(119, '61072212019', 119, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-24', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee059', '', '', '', ''),
(120, '61072212020', 120, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-25', '', '', 'B.E', 'Female', '', 'Electrical and Electronic Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021eee060', '', '', '', ''),
(121, '61072212021', 121, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-26', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece001', '', '', '', ''),
(122, '61072212022', 122, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-27', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece002', '', '', '', ''),
(123, '61072212023', 123, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-28', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece003', '', '', '', ''),
(124, '61072212024', 124, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-29', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece004', '', '', '', ''),
(125, '61072212025', 125, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-30', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece005', '', '', '', ''),
(126, '61072212026', 126, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-03-31', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece006', '', '', '', '');
INSERT INTO `student` (`id`, `regno`, `tcno`, `sname`, `gname`, `contact`, `address`, `community`, `cast`, `dob`, `class`, `shift`, `grad`, `gender`, `blgroup`, `division`, `religion`, `doa`, `college`, `nation`, `lastyear`, `highclass`, `fees`, `scholarship`, `medical`, `medium`, `lid`, `tcapply`, `tcd`, `conduct`, `acdyear`, `tc_generated`, `admno`, `addept`, `adyear`, `tcyear`, `status`) VALUES
(127, '61072212027', 127, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-01', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece007', '', '', '', ''),
(128, '61072212028', 128, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-02', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece008', '', '', '', ''),
(129, '61072212029', 129, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-03', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece009', '', '', '', ''),
(130, '61072212030', 130, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-04', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece010', '', '', '', ''),
(131, '61072212031', 131, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-05', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece011', '', '', '', ''),
(132, '61072212032', 132, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-06', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece012', '', '', '', ''),
(133, '61072212033', 133, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-07', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece013', '', '', '', ''),
(134, '61072212034', 134, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-08', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece014', '', '', '', ''),
(135, '61072212035', 135, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-09', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece015', '', '', '', ''),
(136, '61072212036', 136, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-10', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece016', '', '', '', ''),
(137, '61072212037', 137, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'SC', '2002-04-11', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece017', '', '', '', ''),
(138, '61072212038', 138, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-12', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece018', '', '', '', ''),
(139, '61072212039', 139, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-13', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece019', '', '', '', ''),
(140, '61072212040', 140, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-14', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece020', '', '', '', ''),
(141, '61072212041', 141, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-15', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece021', '', '', '', ''),
(142, '61072212042', 142, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-16', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece022', '', '', '', ''),
(143, '61072212043', 143, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-17', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece023', '', '', '', ''),
(144, '61072212044', 144, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-18', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece024', '', '', '', ''),
(145, '61072212045', 145, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-19', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece025', '', '', '', ''),
(146, '61072212046', 146, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-20', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece026', '', '', '', ''),
(147, '61072212047', 147, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-21', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece027', '', '', '', ''),
(148, '61072212048', 148, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-22', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece028', '', '', '', ''),
(149, '61072212049', 149, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'ST', '2002-04-23', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece029', '', '', '', ''),
(150, '61072212050', 150, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-24', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece030', '', '', '', ''),
(151, '61072212051', 151, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-25', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece031', '', '', '', ''),
(152, '61072212052', 152, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-26', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece032', '', '', '', ''),
(153, '61072212053', 153, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-27', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece033', '', '', '', ''),
(154, '61072212054', 154, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-28', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece034', '', '', '', ''),
(155, '61072212055', 155, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-29', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece035', '', '', '', ''),
(156, '61072212056', 156, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-04-30', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece036', '', '', '', ''),
(157, '61072212057', 157, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-01', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece037', '', '', '', ''),
(158, '61072212058', 158, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-02', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece038', '', '', '', ''),
(159, '61072212059', 159, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-03', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece039', '', '', '', ''),
(160, '61072212060', 160, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-04', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece040', '', '', '', ''),
(161, '61072212061', 161, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-05', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece041', '', '', '', ''),
(162, '61072212062', 162, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-06', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece042', '', '', '', ''),
(163, '61072212063', 163, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-07', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece043', '', '', '', ''),
(164, '61072212064', 164, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-08', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece044', '', '', '', ''),
(165, '61072212065', 165, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-09', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece045', '', '', '', ''),
(166, '61072212066', 166, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-10', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece046', '', '', '', ''),
(167, '61072212067', 167, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-11', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece047', '', '', '', ''),
(168, '61072212068', 168, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-12', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece048', '', '', '', ''),
(169, '61072212069', 169, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-13', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece049', '', '', '', ''),
(170, '61072212070', 170, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-14', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece050', '', '', '', ''),
(171, '61072212071', 171, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-15', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece051', '', '', '', ''),
(172, '61072212072', 172, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-05-16', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece052', '', '', '', ''),
(173, '61072212073', 173, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-17', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece053', '', '', '', ''),
(174, '61072212074', 174, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-18', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece054', '', '', '', ''),
(175, '61072212075', 175, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-19', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece055', '', '', '', ''),
(176, '61072212076', 176, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-20', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece056', '', '', '', ''),
(177, '61072212077', 177, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-21', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece057', '', '', '', ''),
(178, '61072212078', 178, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-22', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece058', '', '', '', ''),
(179, '61072212079', 179, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-23', '', '', 'B.E', 'Female', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece059', '', '', '', ''),
(180, '61072212080', 180, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-24', '', '', 'B.E', 'Male', '', 'Electronic and Communication Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021ece060', '', '', '', ''),
(181, '61072212081', 181, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-25', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech001', '', '', '', ''),
(182, '61072212082', 182, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-26', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech002', '', '', '', ''),
(183, '61072212083', 183, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-27', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech003', '', '', '', ''),
(184, '61072212084', 184, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-28', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech004', '', '', '', ''),
(185, '61072212085', 185, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-29', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech005', '', '', '', ''),
(186, '61072212086', 186, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-30', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech006', '', '', '', ''),
(187, '61072212087', 187, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-05-31', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech007', '', '', '', ''),
(188, '61072212088', 188, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-01', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech008', '', '', '', ''),
(189, '61072212089', 189, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-02', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech009', '', '', '', ''),
(190, '61072212090', 190, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-03', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech010', '', '', '', ''),
(191, '61072212091', 191, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-04', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech011', '', '', '', ''),
(192, '61072212092', 192, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-05', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech012', '', '', '', ''),
(193, '61072212093', 193, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-06', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech013', '', '', '', ''),
(194, '61072212094', 194, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-07', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech014', '', '', '', ''),
(195, '61072212095', 195, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-08', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech015', '', '', '', ''),
(196, '61072212096', 196, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-09', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech016', '', '', '', ''),
(197, '61072212097', 197, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-10', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech017', '', '', '', ''),
(198, '61072212098', 198, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-11', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech018', '', '', '', ''),
(199, '61072212099', 199, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-12', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech019', '', '', '', ''),
(200, '61072212100', 200, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-13', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech020', '', '', '', ''),
(201, '61072212101', 201, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-14', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech021', '', '', '', ''),
(202, '61072212102', 202, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-15', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech022', '', '', '', ''),
(203, '61072212103', 203, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'BC', '2002-06-16', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech023', '', '', '', ''),
(204, '61072212104', 204, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-17', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech024', '', '', '', ''),
(205, '61072212105', 205, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-18', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech025', '', '', '', ''),
(206, '61072212106', 206, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-19', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech026', '', '', '', ''),
(207, '61072212107', 207, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-20', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech027', '', '', '', ''),
(208, '61072212108', 208, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-21', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech028', '', '', '', ''),
(209, '61072212109', 209, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-22', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech029', '', '', '', ''),
(210, '61072212110', 210, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-23', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech030', '', '', '', ''),
(211, '61072212111', 211, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-24', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech031', '', '', '', ''),
(212, '61072212112', 212, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-25', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech032', '', '', '', ''),
(213, '61072212113', 213, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-26', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech033', '', '', '', ''),
(214, '61072212114', 214, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-27', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech034', '', '', '', ''),
(215, '61072212115', 215, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-28', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech035', '', '', '', ''),
(216, '61072212116', 216, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-29', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech036', '', '', '', ''),
(217, '61072212117', 217, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-06-30', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech037', '', '', '', ''),
(218, '61072212118', 218, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-01', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech038', '', '', '', ''),
(219, '61072212119', 219, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-02', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech039', '', '', '', ''),
(220, '61072212120', 220, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-03', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech040', '', '', '', ''),
(221, '61072212121', 221, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-04', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech041', '', '', '', ''),
(222, '61072212122', 222, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-05', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech042', '', '', '', ''),
(223, '61072212123', 223, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-06', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech043', '', '', '', ''),
(224, '61072212124', 224, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-07', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech044', '', '', '', ''),
(225, '61072212125', 225, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-08', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech045', '', '', '', ''),
(226, '61072212126', 226, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-09', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech046', '', '', '', ''),
(227, '61072212127', 227, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-10', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech047', '', '', '', ''),
(228, '61072212128', 228, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-11', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech048', '', '', '', ''),
(229, '61072212129', 229, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-12', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech049', '', '', '', ''),
(230, '61072212130', 230, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-13', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech050', '', '', '', ''),
(231, '61072212131', 231, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-14', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech051', '', '', '', ''),
(232, '61072212132', 232, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-15', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech052', '', '', '', ''),
(233, '61072212133', 233, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-16', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech053', '', '', '', ''),
(234, '61072212134', 234, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-17', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech054', '', '', '', ''),
(235, '61072212135', 235, 'vijay', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-18', '', '', 'B.E', 'Male', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech055', '', '', '', ''),
(236, '61072212136', 236, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-19', '', '', 'B.E', 'Female', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech056', '', '', '', ''),
(237, '61072212137', 237, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-20', '', '', 'B.E', 'Female', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech057', '', '', '', ''),
(238, '61072212138', 238, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-21', '', '', 'B.E', 'Female', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech058', '', '', '', ''),
(239, '61072212139', 239, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-22', '', '', 'B.E', 'Female', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech059', '', '', '', ''),
(240, '61072212140', 240, 'anu', 'murugan', '', '', 'REFER COMMUNITY CERTIFICATE ISSUED BY REVENUE AUTHORITIES', 'MBC', '2002-07-23', '', '', 'B.E', 'Female', '', 'Mechnical Engineering', 'hindu', '0000-00-00', 'GOVERNMENT COLLEGE OF ENGINEERING BARGUR,KRISHNAGIRI', 'INDIAN', '', 'Refer Mark Sheets', '', '', '', 'English', NULL, NULL, NULL, '', '', 0, '2021mech060', '', '', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `tclist`
--

CREATE TABLE `tclist` (
  `id` int(50) NOT NULL,
  `regno` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tclist`
--

INSERT INTO `tclist` (`id`, `regno`) VALUES
(65, '61072211901'),
(66, '61072211901'),
(67, '61072211901'),
(68, '61072211901');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `student`
--
ALTER TABLE `student`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `regno` (`regno`),
  ADD UNIQUE KEY `tcno` (`tcno`);

--
-- Indexes for table `tclist`
--
ALTER TABLE `tclist`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `student`
--
ALTER TABLE `student`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=241;

--
-- AUTO_INCREMENT for table `tclist`
--
ALTER TABLE `tclist`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=69;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
